name: MetroHero Webapp CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.SREPETSK_PAT }}

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '10.24.1'

      - name: Install Gulp-CLI
        run: npm install gulp-cli@^2.3.0 -g

      - name: NPM Install
        run: npm install

      - name: Archive project
        uses: actions/upload-artifact@v3
        with:
          name: metrohero-webapp
          path: dist/
